{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio-multiplatform/2.6.0/okio-multiplatform-2.6.0.module",
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "uq4xtxw34nhrli5ohrpwvbosta"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-2.6.0.jar",
          "url": "okio-2.6.0.jar",
          "size": 243330,
          "sha512": "9d592ad17e09bb8cdd6490d42c8274ceddbaf6c70e0704dde0745501fcc5f5c88f0a7825257b6fab1221e6dcb8e149815750a5f71c81eef67a6df4aebda1ca40",
          "sha256": "4d84ef686277b58eb05691ac19cd3befa3429a27274982ee65ea0f07044bcc00",
          "sha1": "0f06923d428f3c8e6f571043ec29a45d0cd9d2bf",
          "md5": "0e259823ad4d04c10ccd730c712bbb8d"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-2.6.0.jar",
          "url": "okio-2.6.0.jar",
          "size": 243330,
          "sha512": "9d592ad17e09bb8cdd6490d42c8274ceddbaf6c70e0704dde0745501fcc5f5c88f0a7825257b6fab1221e6dcb8e149815750a5f71c81eef67a6df4aebda1ca40",
          "sha256": "4d84ef686277b58eb05691ac19cd3befa3429a27274982ee65ea0f07044bcc00",
          "sha1": "0f06923d428f3c8e6f571043ec29a45d0cd9d2bf",
          "md5": "0e259823ad4d04c10ccd730c712bbb8d"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../okio-metadata/2.6.0/okio-metadata-2.6.0.module",
        "group": "com.squareup.okio",
        "module": "okio-metadata",
        "version": "2.6.0"
      }
    }
  ]
}
